version: '3.8'

volumes:
  redis_data_prod:

x-app: &prod-service
  logging:
    driver: "json-file"
    options:
      max-file: "3"
      max-size: "10m"
  restart: "always"

services:
  chat_history: &prod-app
    <<: *prod-service
    build:
      context: ../chat_history
      dockerfile: ./Dockerfile
    env_file:
      - .env

  bot:
    <<: *prod-app
    build:
      context: ../bot
      dockerfile: ./Dockerfile

  redis:
    <<: *prod-service
    image: redis:6.0.8-alpine
    # After 900 seconds (15 minutes) if at least 1 key changed
    # After 3600 seconds (1 hour) if at least 1 key changed
    # After 300 seconds (5 minutes) if at least 100 keys changed
    # After 60 seconds (1 minute) if at least 1 key changed
    command: redis-server --save 900 1 --save 3600 1 --save 300 100 --save 60 1
    volumes:
      - redis_data_prod:/data
