version: '3.8'

volumes:
  redis_data_prod:

x-app: &prod-service
  logging:
    driver: "json-file"
    options:
      max-file: "3"
      max-size: "10m"
  restart: "always"

services:
  chat_history: &prod-app
    <<: *prod-service
    build:
      context: ../chat_history
      dockerfile: ./Dockerfile
    env_file:
      - .env

  bot:
    <<: *prod-app
    build:
      context: ../bot
      dockerfile: ./Dockerfile

  redis:
    <<: *prod-service
    image: redis:6.0.8-alpine
    volumes:
      - redis_data_prod:/data
